language: python
python:
- '3.7'
dist: xenial
install:
- python setup.py install
script:
- python setup.py test
env:
  global:
    - GITHUB_USER=budikpet
    - CTU_USERNAME="budikpet"
    - GHIA_REPO="git@github.com:budikpet/MI-PYT_GHIA.git"
    - GHIA_BRANCH="GHIA_IV"
    - secure: "XGovCRsOaguSdiKOR9ENeZKPggkO0+obI+zGcVfduh7sRVy0+iUHIqL+lb28OxjQegJ0kbfzyx10ceb03rlfEb39IUOwBUdVbEDe467l7BMIf5EXjl9y0R6uTK/qBKummOfLysorhVN75ERPOs4EEAkFtxhzdJD4ieDsSXTl+/tEOAfWiN/SBL7xdRn/aFtEcjUHH07JgASM7Me4fmHfcTHAIaFVZLJKOV0HogEchAEFGoTcHOTx6miEJtDBCJRGAUn8/MS4DQGpL2sNih/q2ibom/FBOMJv7bvjpk2Snte/2mTAN0r/8e9CdsXQ1bBPB1MZsVojEGbSql668/kdVzYMAobxrJFKrxsoJcFXUYbS22F3y93g0KLxK3aWSAsJjbUkf/+XNqNg3i5KgXA0oQvnz2ix+QKmwVgM+ZAcD4dNGvMxGrQSTF+AhQgGh2jb7Qs6GSOxViT7eAeorvGG+WIZ/wyagoS9TMsR0d854+6SI2mMPzs3+ckNMmIkouE3E22QYMRRJlsib6zDCch+n2AYOlH6eouPjD/4ueQ/BDLfT7Sq2BE7DtHwpPGIQ8FONhuIIHZEoFnZiox3yYdqO5Ls8owSlUv5mh8C+x7SlZFo/GJIRXnmCFZHXc7123r3LIJcFCq/szWS+gf3xMNmTTGMUbGPPUzPt00d8U4Pzec="
