language: python
python:
- '3.7'
dist: xenial
install:
- python setup.py install
- python -m pip install .[dev]
script:
- make -C docs doctest
- python setup.py test
env:
  global:
    - GITHUB_USER=budikpet
    - CTU_USERNAME="budikpet"
    - GHIA_REPO="git@github.com:budikpet/MI-PYT_GHIA.git"
    - GHIA_BRANCH="GHIA_V_Docs"
    - secure: "G/4BQ0rqCtU3Nl1Wcg7VwyzXRfLRc8G7fmtrQYUYlFWr+w1AQsk+5tr/IxaZlvZij8IJRg3PvZhTjoPGJmGwYlZz45aqBLqsfyuPkhMFQbGeydxI/WFHwMy/cwNJmekMQoO9s8rwG2PAogj/XnrXu33KWNeSKxKQSMs/DoUrinXigZ66Rnm/PVgE8TkqrLTiC2dXBx/y+yAKOR77SqBtgD+UMDhnTLBvafRQUZ0U+dyANs1eXD3FBIhaNLUYDUAzPMwd85CuX7gc32affhRlzP0pQtwefuEgUGI8j+VleqBSGs1Jb+wRyHIFIx+zqyelQXNaf9jlzbisTw+qD1kTvCmXLOgjwKryYISLolZIiyvCQ4PeEVRbJFhmrqL8Ozv6JAUTzuaJjK7UTKmmeLiBak5yYh9FFr3ieGdamp6l6WyRP0aXrasw6LH6b0GxsV2yQdU9ci38P1y79mSeN+BU8RbIF7aBi6qGJ4pXNHGPqOVZHCdPBq8MIb8LEr7KBBxZ1j4IUYbbByxDVWNMeE9scQmj7LyQWdggJoLSVum9ZNPpluFeMglfCDzVfUSxiki8aDKa7p5kQTTo7mDepyYAO2ZewMNtf2uw7NjboUVQj8Q1mEN6gSIN1lknsQZp/6pgKOr/jqNSdo2X4rfZrFR/VkWJEL3V7Ms+jJCLfNB/ogg="